const {chromium}=require('C:/Users/rudgn/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
(async()=>{const root=path.resolve(__dirname,'..');const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1280,height:720},hasTouch:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const checks=[];
await page.goto(pathToFileURL(path.join(root,'prototypes/input-lab.html')).href);const cdp=await context.newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:10});
const point=async(owner,action)=>page.locator(`[data-action="${action}"][data-owner="${owner}"]`).evaluate(el=>{const r=el.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};});
const send=(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});
let layoutCases=0;
for(const [width,height] of [[1280,720],[1366,768],[1920,1080]]){await page.setViewportSize({width,height});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));for(let n=1;n<=6;n++)for(const pct of [60,65,80]){await page.evaluate(({n,pct})=>lab.start(n,pct),{n,pct});const boxes=await page.locator('[data-action]').evaluateAll(els=>els.map(el=>{const r=el.getBoundingClientRect(),p=el.parentElement.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,b:r.bottom,right:r.right,px:p.x,pr:p.right};}));for(const b of boxes){assert(b.y>=height*pct/100-.5);assert(b.b<=height+.5);assert(b.w>=64&&b.h>=64);assert(b.x>=b.px-.5&&b.right<=b.pr+.5);assert(b.right<=width+.5);}assert.equal(boxes.length,n*2);layoutCases++;}}
checks.push('54 player/viewport/reach layouts have no upper or undersized student targets');
await page.setViewportSize({width:1280,height:720});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.evaluate(()=>lab.start(6,65));
let starts=[],ends=[];for(let i=0;i<6;i++){starts.push({...await point(i,'source'),id:i+1});ends.push({...await point(i,'target'),id:i+1});}
await send('touchStart',starts);let s=await page.evaluate(()=>lab.snapshot());assert.equal(s.pointers,6);assert(s.log.filter(x=>x[0]==='down').every(x=>x[4]));assert(s.log.some(x=>x[3]===false));await send('touchMove',ends);await send('touchEnd',[]);s=await page.evaluate(()=>lab.snapshot());assert.deepEqual(s.players.map(p=>p.score),[1,1,1,1,1,1]);checks.push('six simultaneous trusted CDP touch drags including non-primary pointers score independently');
await page.evaluate(()=>lab.start(6,65));await send('touchStart',starts);await send('touchMove',starts.map((p,i)=>({...ends[(i+1)%6],id:p.id})));await send('touchEnd',[]);assert.deepEqual((await page.evaluate(()=>lab.snapshot())).players.map(p=>p.score),[0,0,0,0,0,0]);checks.push('cross-lane releases cannot score for another owner');
await page.evaluate(()=>lab.start(6,65));await send('touchStart',starts);await send('touchCancel',[]);assert.equal((await page.evaluate(()=>lab.snapshot())).pointers,0);checks.push('touchCancel clears six captures');
await page.evaluate(()=>lab.start(6,65));await send('touchStart',starts);await page.evaluate(()=>lab.pause());await send('touchEnd',[]);assert.deepEqual((await page.evaluate(()=>lab.snapshot())).players.map(p=>p.score),[0,0,0,0,0,0]);checks.push('pause while six fingers held prevents stale release');
await page.evaluate(()=>lab.start(6,65));await send('touchStart',starts);await page.evaluate(()=>lab.start(6,65));await send('touchEnd',[]);assert.equal((await page.evaluate(()=>lab.snapshot())).players.reduce((n,p)=>n+p.score,0),0);checks.push('restart while held rejects previous-round input');
await page.evaluate(()=>lab.start(6,65));await send('touchStart',starts);await page.evaluate(()=>lab.next());await send('touchMove',ends);await send('touchEnd',[]);assert.equal((await page.evaluate(()=>lab.snapshot())).players.reduce((n,p)=>n+p.score,0),0);checks.push('next question while held rejects previous-question input');
await page.evaluate(()=>lab.start(6,65));await send('touchStart',starts);await send('touchEnd',[]);await send('touchStart',ends);await send('touchEnd',[]);assert.deepEqual((await page.evaluate(()=>lab.snapshot())).players.map(p=>p.score),[1,1,1,1,1,1]);checks.push('six simultaneous tap-then-tap connections work');
await page.evaluate(()=>lab.start(6,65));await send('touchStart',[starts[0],{...starts[0],x:starts[0].x+8,id:7},...starts.slice(1)]);assert.equal((await page.evaluate(()=>lab.snapshot())).pointers,6);await send('touchCancel',[]);checks.push('seventh contact in occupied lane cannot block six owners');
await page.evaluate(()=>lab.start(6,65));await send('touchStart',starts);await page.setViewportSize({width:1366,height:768});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await send('touchEnd',[]);assert.equal((await page.evaluate(()=>lab.snapshot())).phase,'paused');checks.push('viewport resize pauses active input');
await page.evaluate(()=>lab.start(6,65));await page.locator('[data-owner="0"][data-action="source"]').focus();await page.keyboard.press('Enter');await page.locator('[data-owner="0"][data-action="target"]').focus();await page.keyboard.press('Space');assert.equal((await page.evaluate(()=>lab.snapshot())).players[0].score,1);checks.push('keyboard alternative has no duplicate click score');
await page.evaluate(()=>lab.start(6,65));await page.locator('[data-owner="0"][data-action="source"]').click();await page.locator('[data-owner="0"][data-action="target"]').click();assert.equal((await page.evaluate(()=>lab.snapshot())).players[0].score,1);checks.push('native mouse pointer plus compatibility click scores only once');
await page.evaluate(()=>{lab.start(6,65);for(let i=0;i<6;i++){const el=document.querySelector(`[data-owner="${i}"][data-action="source"]`),r=el.getBoundingClientRect();el.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:200+i,pointerType:'touch',clientX:r.x+r.width/2,clientY:r.y+r.height/2}));}const target=document.querySelector('[data-owner="0"][data-action="target"]'),r=target.getBoundingClientRect();target.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:200,pointerType:'touch',clientX:r.x+r.width/2,clientY:r.y+r.height/2}));});s=await page.evaluate(()=>lab.snapshot());assert.equal(s.players[0].score,1);assert.equal(s.pointers,5);checks.push('synthetic DOM test: one player completing leaves five other held contacts intact');
await context.setOffline(true);await page.reload();await page.evaluate(()=>lab.start(6,65));assert.equal((await page.evaluate(()=>lab.snapshot())).players.length,6);checks.push('local standalone file reloads offline');
await page.screenshot({path:path.join(root,'docs/verification/input-lab.png')});assert.deepEqual(errors,[]);await browser.close();fs.writeFileSync(path.join(root,'docs/verification/input-browser.json'),JSON.stringify({engine:'Chromium via Playwright/CDP',physicalHardware:false,layoutCases,checks,errors,passed:true},null,2));console.log(JSON.stringify({layoutCases,checks:checks.length,passed:true}));})().catch(e=>{console.error(e);process.exit(1)});

