const {chromium}=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
(async()=>{const root=path.resolve(__dirname,'..'),browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage();const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.goto(pathToFileURL(path.join(root,'prototypes/generator-design.html')).href);const checks=[];
assert.equal(await page.title(),'수학 공작소');assert.equal(await page.locator('header .brand').textContent(),'M수학 공작소');assert.equal(await page.locator('.intro-label').textContent(),'활동지 1개로, 선생님이 원하는 게임을 디자인하세요.');assert.equal(await page.locator('.intro h1').textContent(),'수학 게임 공작소');assert.equal(await page.locator('.intro p').textContent(),'선생님의 취향에 맞게 프롬프트를 만들어줄거에요.');checks.push('product name and requested three-line introduction are exact');assert.equal(await page.locator('footer.site-footer').count(),1);assert.equal(await page.locator('footer.site-footer').textContent(),'© 2026 찰떡쌤. All rights reserved.');assert(await page.locator('footer.site-footer').evaluate(el=>el.previousElementSibling.tagName==='MAIN'&&getComputedStyle(el).position==='static'));checks.push('copyright appears once after main content in normal page flow');
assert.equal(await page.locator('#featured .game').count(),20);assert.equal(await page.locator('#featured .game:visible').count(),8);await page.locator('#games-toggle').click();assert.equal(await page.locator('#featured .game:visible').count(),20);await page.locator('#games-toggle').click();assert.equal(await page.locator('#featured .game:visible').count(),8);checks.push('8 initial genres expand to 20 and collapse without losing controls');await page.locator('#featured [data-game=quiz]').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.dataset.game),'quiz');checks.push('genre selection preserves keyboard focus');assert.equal(await page.locator('#themes button').count(),12);await page.locator('#catalog-open').click();assert.equal(await page.locator('#catalog-list .game').count(),20);await page.locator('#search').fill('잇기');assert.equal(await page.locator('#catalog-list .game').count(),1);await page.locator('#catalog-list [data-game="match"]').click();assert.equal(await page.locator('#recipe-name').textContent(),'선 잇기');assert(!await page.locator('#catalog').evaluate(el=>el.open));checks.push('all 20 genres searchable and selection updates recipe');
await page.locator('#players button[data-value="6"]').click();await page.locator('#mode').selectOption('coop');await page.locator('#duration').selectOption('90');await page.locator('#themes button[data-value="forest"]').click();assert.equal(await page.locator('#theme-preview .preview-lane').count(),6);const out=await page.evaluate(()=>generator.getOutput());for(const s of ['6명 동시 참여','90초','공동 목표','정글 어드벤처','정글 경로·탐험 배지·보물 조각','상단 HUD'])assert(out.includes(s));checks.push('participant, mode, duration and game-theme contract propagate to preview and prompt');assert.equal(await page.locator('#themes svg').count(),0);assert.equal(await page.locator('#themes .theme-icon').count(),12);assert.equal(await page.locator('#themes .theme-words small').count(),12);assert.equal(await page.locator('main .board svg').count(),1);for(const s of ['STAGE 2','MISSION 04','★ 3 · 90초'])assert((await page.locator('#theme-preview').textContent()).includes(s));await page.locator('#theme-open').click();assert(await page.locator('#theme-dialog').evaluate(el=>el.open));assert.equal(await page.locator('#theme-large-name').textContent(),'정글 어드벤처');await page.keyboard.press('Escape');checks.push('12 game-world choices, one HUD scene preview and enlargement work');
await page.locator('summary').click();await page.locator('#scope2').fill('둘째 자료 2쪽');await page.locator('#idea').fill('</script><img src=x onerror=alert(1)> {{teacher_settings}}');assert.equal(await page.locator('img').count(),0);await page.locator('#idea').fill('함께 다리를 완성해요');await page.locator('summary').click();checks.push('free text remains data without HTML execution');
await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(Error('denied'))},configurable:true}));await page.locator('#copy').click();assert(await page.locator('#prompt-dialog').evaluate(el=>el.open));assert.equal(await page.locator('#prompt-text').inputValue(),await page.evaluate(()=>generator.getOutput()));checks.push('clipboard denial opens complete selectable fallback');await page.keyboard.press('Escape');assert(!await page.locator('#prompt-dialog').evaluate(el=>el.open));assert.equal(await page.evaluate(()=>document.activeElement.id),'copy');checks.push('dialog Escape closes and returns focus');
const downloadEvent=page.waitForEvent('download');await page.locator('#download').click();const download=await downloadEvent;const downloaded=fs.readFileSync(await download.path(),'utf8').replace(/^\uFEFF/,'');assert.equal(downloaded,await page.evaluate(()=>generator.getOutput()));checks.push('UTF-8 TXT download matches current compiled prompt');
await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copied=text;}},configurable:true}));await page.locator('#copy').click();assert.equal(await page.evaluate(()=>window.copied),await page.evaluate(()=>generator.getOutput()));assert((await page.locator('#status').textContent()).startsWith('프롬프트를 복사했습니다'));checks.push('successful clipboard adapter reports success only after promise resolution');
await page.locator('#players button[data-value="1"]').click();await page.locator('#mode').selectOption('teams');assert.equal(await page.locator('#recipe-mode').textContent(),'개인 도전');checks.push('one-player team selection visibly resolves to solo');
await page.locator('#players button[data-value="4"]').click();await page.locator('#mode').selectOption('coop');
const scenes=[];for(const id of Object.keys(await page.evaluate(()=>generator.compiler.data.themes))){await page.locator(`#themes button[data-value="${id}"]`).click();const text=await page.evaluate(()=>generator.getOutput());const contract=await page.evaluate(id=>generator.compiler.data.themes[id].visualContract,id);assert(text.includes(contract));scenes.push(await page.locator('#theme-preview svg').getAttribute('aria-label'));assert.equal(await page.locator('#theme-preview .preview-lane').count(),4);}assert.equal(new Set(scenes).size,12);await page.locator('#themes button[data-value="forest"]').click();checks.push('all 12 scene descriptions share the visual contract with the compiled prompt');
assert.equal(await page.locator('#sound,#motion').count(),0);const fixed=await page.evaluate(()=>generator.getOutput());for(const text of ['소리: 켬','움직임 줄이기: 시스템 설정 따름','오답 확정','정답 +10점','오답 −5점','1.2초','시각 디자인 합격 기준'])assert(fixed.includes(text));checks.push('fixed audio and system motion, explicit wrong-answer penalty and visual requirements reach exported prompt');
const layouts=[];for(const [width,height] of [[1440,1000],[1366,768],[1024,768],[768,1024],[390,844],[320,900]]){await page.setViewportSize({width,height});await page.evaluate(()=>window.scrollTo(0,0));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));const clip=await page.locator('button,select,input').evaluateAll(els=>els.filter(el=>el.getClientRects().length&&!el.closest('dialog')).filter(el=>el.scrollWidth>el.clientWidth+2).map(el=>el.id||el.textContent));assert.deepEqual(clip,[]);layouts.push({width,height,horizontalOverflow:false});if(width===1440){await page.screenshot({path:path.join(root,'docs/verification/generator-desktop.png')});await page.locator('#themes').screenshot({path:path.join(root,'docs/verification/theme-gallery.png')});}if([1440,390].includes(width))await page.screenshot({path:path.join(root,`docs/verification/generator-${width}.png`),fullPage:true});}
checks.push('six responsive widths including 320 CSS px avoid horizontal overflow and clipped controls');
await page.setViewportSize({width:683,height:384});await page.evaluate(()=>window.scrollTo(0,0));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('#copy').scrollIntoViewIfNeeded();assert(await page.locator('#copy').isVisible());checks.push('200 percent equivalent CSS viewport keeps primary action reachable');
await context.setOffline(true);await page.reload();assert((await page.evaluate(()=>generator.getOutput())).includes('undefined')===false);assert((await page.evaluate(()=>generator.getOutput())).includes('[완성할 결과]'));assert(requests.every(url=>url.startsWith('file:')));checks.push('standalone offline load makes no external requests');assert.deepEqual(errors,[]);await browser.close();const report={kind:'prototype browser UI, not teacher usability study',checks,layouts,errors,externalRequests:0,passed:true};fs.writeFileSync(path.join(root,'docs/verification/design-browser.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));})().catch(e=>{console.error(e);process.exit(1)});

